# Generated by Django 5.0.7 on 2024-08-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('pk',), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='finished_at',
            field=models.DateField(blank=True, help_text='В формате 2024-08-04', null=True, verbose_name='Дата окончания рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mailing_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема рассылки'),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(help_text='Выбрать сообщение для рассылки', on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailingservice.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='started_at',
            field=models.DateField(help_text='В формате 2024-08-04', verbose_name='Дата начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='создана', help_text='Узнать статус рассылки', max_length=50, verbose_name='Статус рассылки'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastattempt_at', models.DateTimeField(auto_now_add=True, help_text='В формате 2024-08-04', verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('SUCCESS', 'успешно'), ('NOT SUCCESS', 'не успешно')], default='NOT SUCCESS', help_text='Узнать статус попытки', max_length=50, verbose_name='Статус попытки')),
                ('server_answer', models.TextField(blank=True, max_length=2550, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailingservice.mailing', verbose_name='Рассылки')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(help_text='Выбрать клиента', related_name='mailings', to='mailingservice.client', verbose_name='Клиенты'),
        ),
    ]
