# Generated by Django 5.1 on 2024-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingservice', '0005_mailing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='time',
            field=models.TimeField(default='12:00', help_text='В формате 2024-08-04', verbose_name='Время запуска'),
            preserve_default=False,
        ),
    ]
