# Generated by Django 5.1 on 2024-09-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingservice', '0006_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(help_text='В формате 12:00:00', verbose_name='Время запуска'),
        ),
    ]
