# Generated by Django 5.1 on 2024-09-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailingservice', '0007_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
    ]
